name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: chatbot
          POSTGRES_PASSWORD: chatbot
          POSTGRES_DB: chatbot
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U chatbot" --health-interval 5s --health-timeout 5s --health-retries 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Sync deps
        run: |
          uv python install 3.13
          uv sync --all-extras
      - name: Run backend
        env:
          OPENAI_API_KEY: dummy
          DATABASE_URL: postgresql+psycopg://chatbot:chatbot@localhost:5432/chatbot
          LOG_LEVEL: INFO
          API_KEY: test-key
        run: |
          nohup uv run --python 3.13 python main.py --host 0.0.0.0 --port 8000 >/dev/null 2>&1 &
          sleep 5
      - name: Run tests
        env:
          TEST_API_BASE: http://localhost:8000
          API_KEY: test-key
        run: |
          uv run --python 3.13 pytest -q
